### ISSUE TITLE
1.6.0 Horizontal Birch/Cherry Bar Textures

### ISSUE THREAD

**Issue by Virtualhel** [gamma1772/AdditionalBars#19]
The Horizontal Birch Bars have the same texture as the Horizontal Crossed Birch Bars, as do the Horizontal Cherry Bars and the Horizontal Crossed Cherry Bars.

**Screenshots**
![2021-03-03_16 33 03](https://user-images.githubusercontent.com/79956056/109881941-b4ea4280-7c3e-11eb-9534-bf4f4259af07.png)
![2021-03-03_16 33 05](https://user-images.githubusercontent.com/79956056/109881984-c5022200-7c3e-11eb-890f-2dcd368eb6da.png)
![2021-03-03_16 30 06](https://user-images.githubusercontent.com/79956056/109882003-cb909980-7c3e-11eb-9200-09be146778c6.png)
![2021-03-03_16 30 09](https://user-images.githubusercontent.com/79956056/109882010-cf242080-7c3e-11eb-912f-b5bcc739740d.png)

**Comment by CodenameRevy** [comment]
This will be fixed in the next release, since I'm switching to a different bars models.
