### ISSUE TITLE
[1.18.2] Copper bars not craftable

### ISSUE THREAD

**Issue by Mitchell5200** [gamma1772/AdditionalBars#23]
As title says, copper bars are not craftable and recipes will not show up in JEI
Tested in a fresh 1.18.2 world with forge 40.1.25, additional bars 3.0.1 Beta+1.18.2 
Also during testing i found that even gold bars were not craftable either, even though the modpack i originally found this issue in has gold bars craftable, and nothing changed for them

**Comment by gamma1772** [comment]
This is intentional because copper bars don't have most of the functionality implemented, such as waxing, stripping and lightning striking.

I'm waiting for https://github.com/MinecraftForge/MinecraftForge/pull/8363 to get merged to implement full functionality and crafting

**Comment by Mitchell5200** [comment]
Okay cool i'll pass that on.
